2022-07-30 11:15:09,682 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:15:09,682 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://localhost/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'lm', 'password': 'LiuM123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:15:13,771 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A6D291420>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:15:13,771 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:15:13,771 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://localhost/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'liuchan', 'password': 'LiuC456', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:15:17,855 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A6D291690>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:15:17,858 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:15:17,858 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://localhost/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'dy', 'password': 'DY123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:15:21,926 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A6D26A5C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:15:21,926 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:15:21,926 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://localhost/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'wangwu', 'password': 'ww123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:15:26,016 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A6D26BAC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2022-07-30 11:15:26,020 - [custom_log.py --> line:61] - INFO : case_name:get_cmdopts
2022-07-30 11:15:26,020 - [custom_log.py --> line:62] - INFO : 
method:post
url:http://localhost/WoniuSales_20180508_V1.4_bin/user/login
data:{'username': 'admin', 'password': 'Milor123', 'verifycode': '0000'}
headers:None
host:None
2022-07-30 11:15:30,091 - [custom_log.py --> line:66] - ERROR : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /WoniuSales_20180508_V1.4_bin/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A6D26B190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
